### ISSUE TITLE
Thunderbird "Get Messages" is inconsistent

### ISSUE THREAD

**Issue by rany2** [neilalexander/yggmail#2]
**Describe the bug**
Thunderbird's "Get Messages" button is inconsistent. When it doesn't work it seems like the only solution is to restart Thunderbird. 

**Desktop:**
 - OS: Debian 10
 - Client: Thunderbird
 - Version: 78.11.0

**Additional context**
Might be related to the lack of IMAP Notify support.

**Comment by neilalexander** [comment]
There's some very early support for IMAP NOTIFY in 63de5e81e477ba08734b7cf02b8b278e45f0c19c so please give the latest commit from `main` a try.

Note that it only notifies right now on incoming mail from remote servers and not by changes from other clients right now.

**Comment by rany2** [comment]
I tested with zygon.sisyphus and the latest commit fixed this for me. It works great and there is no need to press on "Get Messages" button anymore.
