### ISSUE TITLE
Running yggmail together with yggdrasil

### ISSUE THREAD

**Issue by xaozai** [neilalexander/yggmail#20]
Please tell me, is it possible to run yggmail on the same computer where yggdrasil is running, without using virtualization?
I think it would be convenient to use a single tun-adapter...

**Comment by neilalexander** [comment]
Yggmail embeds it's own Yggdrasil node and doesn't use TUN, so it is fine to run it on the same machine as regular Yggdrasil.

**Comment by xaozai** [comment]
It is interesting. And how does it work without TUN?

**Comment by neilalexander** [comment]
It uses the embedded Yggdrasil node as a packet transport and carries SMTP over uTP. It doesn't need TUN because it doesn't deal with IP packets.

**Comment by xaozai** [comment]
Ок. Thanks! ;)
